### ISSUE TITLE
What yaml formatter exists anywhere that can format to yamllints specs?

### ISSUE THREAD

**Issue by matthewdeanmartin** [sbaudoin/yamllint#36]
As far as I can tell, yamllint represents a new file format unrecognized by any tool anywhere.

Yaml is normally machine generated and consumed by machines, so it would make more sense for a formatter to also be automatic.

Yet yamllint is integrated into sonar which in a normal installation gives developers no means to modify the rules used. So that leaves campaigning to get it removed from sonar or get yaml formatters across multiple ecosystems to adhere to this idiosyncratic format, a truly herculean effort.

If there is even one tool that exists that can format to this ideosyncratic dialect of yaml, that would help.

**Comment by sbaudoin** [comment]
Hi,

Sorry but I'm not sure I understand your point: you are looking for a tool that would help generating the `.yamllint` file from any other rule engine of definition language, right?

**Comment by matthewdeanmartin** [comment]
No, the ruleset that gets bundled with SonarQube's plugin should be a ruleset that matches the behavior of at least one well known formatter, e.g. prettier.

There should be a formatter, any formatter that exists that can format to your tool's specs. If there is not, then you are asking us to manually edit 1000s of lines of files, continually, forever, because many of these files are machine-generated/machine consumed.

Once you ship yamllint with SonarQube, it shows up in organizations that do not allow their developers to change the .yamllint file or the ruleset. That leaves me in the position of either campaigning to get the yamllint plugin removed or SonarQube removed, but SonarQube generally finds fixable problems except for these yamllint "phantom errors" I can't even file a bug against SonarQube because it isn't a supported plug in.

This compares to the python ecosystem where the tool `black` can format code that `pylint` accepts.  Only hand-editing can generate yaml that yamllint accepts.

**Comment by sbaudoin** [comment]
Hello,

Sorry for the (very) late reply. As far as I know there is no formatter that complies with the yamllint specs. Companies using the SonarQube plugin are encouraged to define YAML coding conventions and write accordingly their own `.yamllint` conf file so that their YAML files are checked against known, shared and accepted in their organizations.

If you do not want the plugin to be executed, you have several options, one being to create a quality profile with no YAML rule and assign it to your project. With SQ 9.2 on, YAML is a known language, meaning that YAML code will now be highlighted by edfault and you have to install the YAML plugin only of you want to check your YAML code.
